Debug CI and config
GandelXIV/RezOS pull request #15
Opened 2024-12-21 15:29 UTC by ElisStaaf

### .github/workflows/build-pass.yml
Typo. In the file a *this* codeblock is executed:
```sh
{insignificant} && python3 smeltile.py
```
`smeltile.py` doesn't exist. Change to `smeltfile.py`.

### config/config.sh
Error. I believe the profile "default" already has all it's options in the .asm and the .S
files. Change to this:
```sh
if [ ! $PROFILE == "$PROFILE_DIR/default" ]; then
    # ...
fi
```

2025-01-07 17:30 UTC, GandelXIV requested changes
Hi, thanks for you contribution. There are some changes needed before we merge this.

2025-01-07 17:30 UTC, GandelXIV commented on config/config.sh
> +PROFILE_DIR="config/profiles"
I believe its better to leave trailing slashes for directory paths, not that it matters much.

2025-01-07 17:30 UTC, GandelXIV commented on .github/workflows/build-pass.yml
> +        run: source $HOME/.cargo/env && python3 smeltfile.py iso
Good catch, was wondering why it didnt work xd

2025-01-07 17:30 UTC, GandelXIV commented on config/config.sh
> +if [ ! $PROFILE == "$PROFILE_DIR/default" ]; then
This step breaks the build process for fresh clones. Config files are not set by default in the git tree, and thus before building it is required to run this script (with `default`) to put them in their places. The default profile is currently the only one, with room for additional in the future. 

TLDR: This line breaks this, consider removing it.

2025-01-07 17:30 UTC, GandelXIV commented on config/config.sh
Hi, if you want to update this code, here are some things that should be added:
- abort when an invalid config profile is supplied
- allow for switching to another config without having to call `deconfig.sh`  first.
- anything you would find useful tbh
Dont forget to test it tho ;P

2025-01-09 17:29 UTC, ElisStaaf commented
Yeah I reverted the config changes because I'm (believe it or not) lazy and tired. Maybe I'll come back in a few weeks with a config pull request but idk really

2025-04-11 14:43 UTC, closed without merging